Revert "build-llvm.py: Update DEFAULT_KERNEL_FOR_PGO to 6.2.8"
Causing build to fail

I: Building Linux 6.2.8 for profiling...
$ make -C /workspace/a3-llvmbuild/src/linux-6.2.8 -skj16 ARCH=arm64 KCFLAGS=-Wno-error LLVM=/workspace/a3-llvmbuild/build/llvm/instrumented/bin/ O=/workspace/a3-llvmbuild/build/llvm/linux defconfig all
init/Kconfig:1367: can't open file "usr/Kconfig"
make[3]: *** [/workspace/a3-llvmbuild/src/linux-6.2.8/scripts/kconfig/Makefile:87: defconfig] Error 1
make[2]: *** [/workspace/a3-llvmbuild/src/linux-6.2.8/Makefile:708: defconfig] Error 2
make[1]: *** [/workspace/a3-llvmbuild/src/linux-6.2.8/Makefile:373: __build_one_by_one] Error 2
make[1]: Target 'defconfig' not remade because of errors.
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:242: __sub-make] Error 2
make: Target 'defconfig' not remade because of errors.
make: Target 'all' not remade because of errors.
Traceback (most recent call last):
  File "./build-llvm.py", line 646, in <module>
    pgo_builder.build()
  File "/workspace/a3-llvmbuild/tc_build/kernel.py", line 342, in build
    builder.build()
  File "/workspace/a3-llvmbuild/tc_build/kernel.py", line 88, in build
    self.run_cmd(make_cmd)
  File "/workspace/a3-llvmbuild/tc_build/builder.py", line 39, in run_cmd
    return subprocess.run(cmd, capture_output=capture_output, check=True, cwd=cwd)
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-C', PosixPath('/workspace/a3-llvmbuild/src/linux-6.2.8'), '-skj16', 'ARCH=arm64', 'KCFLAGS=-Wno-error', 'LLVM=/workspace/a3-llvmbuild/build/llvm/instrumented/bin/', 'O=/workspace/a3-llvmbuild/build/llvm/linux', 'defconfig', 'all']' returned non-zero exit status 2.

This reverts commit c933dec65d26ec24d2257e7cf6c5b9ed53cdfc4f.

Signed-off-by: Disconnnected0 <womhateui@gmail.com>